language: node_js
node_js:
- '12'
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: pfh-copy-backend
  api_key:
    secure: q/aRax4KtKk3hyafpwrWuxNOmiqcofxE6lJQOYMaeSe13bHIFf27ZDM04/CoP7Bg6Gv7Qj3HY3R+En9BG7RSusJ+03NpJ2QQw3rCHGZyHzizn55lZgNIYx3KauwvEmzHCn580mhKc0MEPgQgwBMo3RqQBYxcwzQfF94fiGFxd68BHyw+/xrXTUglGpDFzqoXjvbB5aA+aSnugMRRi2eVU90y57d2tQh0LBp62t7mvCttnRq1wAi/iIGv/34cc89/mPtYIYsmAX2X7iRZJDF2l6eMdL6uWNPG8Ml09H3N+4Z97zfgFK5+GsZhIrRbSVzuVwDfTbT7UziskE2qGGSUlZrMM2xjHeTEDq3fOSZzeN+Rk2BxNGXWHCdHfVHmReSTLja8On+q1HSBP2ZdyIOZnZThZ0yifnBHyrNdtKVsAep9GNE8kUzErkG9KBQZAmF1I/qEEZTR/IWSbTXeRGgwZ+lFkfo1xgfdlCETtOx8H2wKxv7KKxzPx7dJdcTfUbHfB12c+82PMyBhM6NnPxiyXqwgCV8fQJAZet+TfmSC/QDFXezs6qPgHJOJsYYBvn4xxMNdgJG6r8pi2o31hu8RAfTZ/3TvLsjwesaaxYMaRIF0YfLWk3iEVv4bb3t8xEXBQhTNu96ot8G0FkfgclzlL0LIS8Tu8fqUHqtk0fTyu6E=
