language: node_js
node_js:
- '12'
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: wfh-backend
  api_key:
    secure: sUG3sgjR6om26AT8cz/sDzJ7bK433qXeD9vnzQIaTjcjA4xQkYOhAoGpiAE/wxeHQ2kV2goROqnEEJN9xfgk/W3jFsQ7ddq3hBv1YBpEPQc8QNvwkbtonY3iGByB8SGCQyU4VRr8VTYfSjOy7vh+Mhif9intUqRATfjIR4SwbHTDR587gaTEGfZSOl6w2M07XTNuId8NkCo8oeB7kzeG0cRIwhTlp4U1eAj3bZpaQiDszQ2qNgVpR2H2luqJbwgYgm9mZQXx/CQVDScdoyZncSFQxBRCEfRvWCFmab/EgmPU0UFf7O7jcF1shcWgZIi3Ye7+3c/6glYMeZquZi/REyGowNeSm57aCHWCCBNyjJAqA41anmXNTe9ANz+7Axs+ZHjhd46C1W9OzoprBuXxDyJ3iJ7Jrcar0RsSnAdNUOEChce3/zAWZ5nJUwtoG/lLMeutuhymWZyX+momrZW3wkZJmSQNVUvfFkydfVJ2BGOh3E0X8fFv6RK14mozeKRNGtRh0o8L5USDuPlgYseNG9s84z+qV6HtYfjtm/C5x3Vq3CjuW339Hc5OBYdVUhs6s3/A+vglrMK2ywv9RLGXOXRLmDOQEH1w1+vUJcK+7jLC0JzWCOxFycnyHioKq/IEbl1LTf4RUMm+bt1M2MRUBdvwDHV0QmjFtveI9aCyPy8=
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
