language: node_js
node_js:
- '12'
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: pfh-copy-backend
  api_key:
    secure: B+TLj41JcgI/WQ767jw5tYjmqlZJoTeLehTttQLLqDLj2lDLQgG2n3NDxpnd9YNx1xAo6KA9z3j3SMBzshZ0D7Mf72Gqfejgf5cQlfu7a5S6qe3bff1bg8Tu3JwcoT029yE50+NVWGHo0iybcPd8t4aFhvrJ8M37bbtUG6T9gMqR3NobvKOLuUFb72BCU0PQz2VDu09dEgkZxMJ2i3ElI019nUP4KEpg4IXLTrvmD+Z6HYY8kNamRupURoobk9BEPoVeUv62a4a2ejcZLE82NZONJlMItPmCtnjfuq3gRzyimGO0jmTyzDGs9nGECHAZai1+H00Ht1zaovJcMDV1kZyirVZRxzeOzqneFUjF2KGkZzeraE4wtA/EbRPQjDdvpXTKjzflDrtz/G0GCXE2/rCVygik32ItK7kI3BX9IVbd/PQGb44xIPkph9MYcON8Tn+Y4Prh2aKnrBP//1OCpDKV9pnkxA/67KPhtZHEyGN6lCJOcpGDUxDNw3D9SMWx4J12AfaJNYvMp91oBkYlGc2gWABTb3nsd7+zLEuXTZDh6lj/Ptzw38Frx0BMbZ71tdMizk/IfSP5wu6RI+pmymOUpdxR0XANXJxQpruCGzNG24WSnjOEu6uudnmFcZw+9fQ/nW3pj+6Kk2tnoxW2hImMgsoccY/j/CfmeCltQ4I=
